#!/bin/bash
echo "Happy Coding"
echo "Analyzing your skills....."
echo "Approach: Long Term Commitment"
echo "Approach: Insanely Innovative"
echo "Approach: Bruttaly Loyal"
echo "Approach: Exceptional Workaholic"
echo "Approach: Awesome team player"
echo "Yoda: May the force be with you."